### ISSUE TITLE
Localist Integration Questions

### ISSUE THREAD

**Issue by marleen-linares** [ITS-UofIowa/international.uiowa.edu#22]
Hi @joewhitsitt , 

Sorry to make you repeat yourself but I can't seem to find this information in my notes. I have a couple of questions about our localist integration on our website:

1. How far back are events kept archived on our website?
2. The search function does not include archived events, correct?

Thanks, 
Marleen

**Comment by joewhitsitt** [comment]
1. The archive on the site should be 365 days back from today. https://international.uiowa.edu/events/archive?page=7
2. Correct, currently the search on the site is only looking at future events.

On events.uiowa.edu, I believe the search is also limited to future events, but you can use the mini calendar to go back farther than a year. Not sure how long Localist will keep them, but I believe they still go back to when the University transitioned to the service.

**Comment by marleen-linares** [comment]
Hi Joe,
I had another question about our Localist integration. Currently, the formatting applied in Localist (events.uiowa.edu) is not reflected on the event page generated on our website. I've included an example below:

- Original Listing: http://events.uiowa.edu/event/study_abroad_fair_9794#.WVLNrIjyu70

- IP Listing: https://international.uiowa.edu/event/973958

As you can see, the text that is bolded in the original listing is not bolded on the listing on our website. Is this something that could be transferred over automatically?

Thanks!
Marleen

**Comment by joewhitsitt** [comment]
TL;DR Version - Not currently because of security issues, but SiteNow will take a look at working around it in the near future.

--

Localist uses `<b>` (bold) and `<i>` (italic) tags for formatting. When we pull in the event data, we run it through code that filters the HTML to prevent cross-site-scripting (XSS) vulnerabilities. In other words, `<b>` and `<i>` tags are not secure so our code strips them out.

Because it is unlikely Localist will change how they send us the description, I have opened an issue to make a first pass to replace those tags with the secure alternatives `<strong>` (bold) and `<em>` (italic) before running the security check/strip. 

Some assumptions can be made that the data they are sending us has already been through some type of sanitization, and that anything malicious would be attached to an authenticated account.

**Comment by marleen-linares** [comment]
Sounds good, thanks Joe.

**Comment by joewhitsitt** [comment]
Bold and Italics are now supported. Instead of waiting for Localist, we are converting on the fly.

![screen shot 2017-10-18 at 11 37 29 am](https://user-images.githubusercontent.com/4663676/31730836-ca066048-b3f8-11e7-8bfd-2691ce22add3.png)
